### ISSUE TITLE
Upgrade ArchivesSpace to 3.5.0

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#176] opened 2024-03-15 20:14 UTC
Please upgrade our ArchivesSpace instance to 3.5.0.  

I would prefer that we upgrade test first and do some testing before deploying to production to be sure the new version doesn't break any local configurations or plug-ins developed in house.

We are currently on 3.3.1.

Release notes and download: https://archivesspace.org/archives/8469

**Comment by abelemlih** [comment] 2024-05-03 18:20
@erussey I emailed the Lyrasis team to request upgrading the Test instance to v3.5.0 of ArchivesSpace. Please refer to this release for the updated configuration: https://github.com/emory-libraries/aspace-deployment/releases/tag/v2024-05-03

**Comment by abelemlih** [comment] 2024-05-10 17:33
@erussey ArchivesSpace 3.5.0 is ready for testing on the Test instance. Once approved, I will reach out to Lyrasis for a deploy to production

**Comment by erussey** [comment] 2024-05-31 13:09
@abelemlih : There's something in our plug-in for the front end that isn't working.  If you look at a resource in the PUI, the Collection organization menu on the right just spins: https://archives-test.libraries.emory.edu/repositories/7/resources/2609

I talked to Lyrasis about this and they attempted a restart and a reindex, but the issue is still there.  They suspect that there is an issue with one of our front end plug-ins in the new ASpace version.  They aren't seeing any errors in the logs but are seeing errors in the browser:

<img width="1642" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEFwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--25886ea41dd152c0e6a9d1dd6df7f1f6a55c8106/Screenshot%202024-05-31%20at%209.09.02%E2%80%AFAM.png" alt="Screenshot 2024-05-31 at 9.09.02 AM.png" />

**Comment by erussey** [comment] 2024-05-31 13:21
There may also be a discrepancy between the config files between test and prod.  Digital object menus are showing up in test but not in prod.  It seems to be this setting that may be set in prod and not in test? https://github.com/archivesspace/archivesspace/blob/master/common/config/config-defaults.rb#L502

**Comment by erussey** [comment] 2024-05-31 13:51
Another issue is the menus in the PUI are not displaying the names of the repositories:
<img width="898" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGNwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8eab82c042e3f47d6679b5defac1917a98400e99/Screenshot%202024-05-31%20at%209.50.48%E2%80%AFAM.png" alt="Screenshot 2024-05-31 at 9.50.48 AM.png" />

**Comment by erussey** [comment] 2024-06-26 19:48
@abelemlih : Where are we on making the necessary changes to upgrade ASpace?  Clare has done some work on the help documentation and I want to be sure it doesn't collide with the work being done on this ticket.

**Comment by abelemlih** [comment] 2024-06-26 20:28
@erussey I am going to work on resolving the bugs highlighted above on Friday. My plan is to dedicate the whole day to Aspace enhancements so we can retest the upgrade soon.

**Comment by erussey** [comment] 2024-06-26 20:37
Summary of identified bugs during testing (more info and screenshots in previous comments):

- Collection organization tab does not load, preventing view of individual archival objects
- Configuration files between test and prod do not match (see digital object menus)
- Repository names not appearing in the filter and the repository browse (using browse in the header) leads to an error message rather than a display of the repositories

**Comment by abelemlih** [comment] 2024-07-01 18:13
@erussey I have been working on resolving the issues above, and the following are my findings:

**Collection organization tab does not load, preventing view of individual archival objects**

I was able to reproduce this issue locally, and found a solution. On my local, you can now see the collection organization as shown below

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGFrQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2507177d8523225d7193e3fb9d4b5c19b21b2fbd/Screenshot%202024-07-01%20at%201.07.34%E2%80%AFPM.png" alt="Screenshot 2024-07-01 at 1.07.34 PM.png" />

**Configuration files between test and prod do not match (see digital object menus)**

I am not sure what the issue exactly is. We current do not set `AppConfig[:pui_hide][:digital_object_badge]` in any of our configuration files. It is set by default in the ArchivesSpace repository: `AppConfig[:pui_hide][:digital_object_badge] = false`

**Repository names not appearing in the filter and the repository browse (using browse in the header) leads to an error message rather than a display of the repositories**

I was not able to reproduce this issue locally. As seen below, I see the repositories by name and can access the repositories through Browse:

<img width="474" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG1rQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be36d694a772011830faa46ed152113ec15fc205/Screenshot%202024-07-01%20at%201.09.30%E2%80%AFPM.png" alt="Screenshot 2024-07-01 at 1.09.30 PM.png" />

<img width="1638" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHFrQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--13b7de292d5a73ef0f77e728b66f8c9c5f9eb9bb/Screenshot%202024-07-01%20at%201.09.49%E2%80%AFPM.png" alt="Screenshot 2024-07-01 at 1.09.49 PM.png" />

I am not sure what exactly the issue here is, if anything, it could be something wrong in the Test environment. We may need additional guidance from the Lyrasis team since I cannot reproduce it, and we currently do not override the view where it is rendered: https://github.com/archivesspace/archivesspace/blob/master/public/app/views/shared/_only_facets.html.erb

Also, I noticed on the ArchivesSpace repository that they recently resolve some issues with the facets view where the repository names don't show, in this PR: https://github.com/archivesspace/archivesspace/pull/3238. I am not sure if this concerns us and/or whether we should for wait for another bug fix release that contains these changes.

**Comment by erussey** [comment] 2024-07-02 19:45
@abelemlih : So glad you figured out the issue with the collection organization.  Since you can't reproduce the other two, would it be possible to push through the first fix to test (along with the merged changes from @CB987) which might make it easier to address the second and third with Lyrasis?  That would also help us test whether the Aeon plug-in is working properly which we have been unable to do thus far.

**Comment by abelemlih** [comment] 2024-07-03 14:49
@erussey I will reach out to Lyrasis with a deploy request to Test, with all the latest changes. Thanks!

**Comment by abelemlih** [comment] 2024-07-05 17:11
@erussey  Deploy request sent to Lyrasis to deploy [v2024-07-05](https://github.com/emory-libraries/aspace-deployment/releases/tag/v2024-07-05) to Test. This version includes the fix for collection organization tab as well as Clare's latest help page changes.

**Comment by abelemlih** [comment] 2024-07-15 20:46
[v2024-07-05](https://github.com/emory-libraries/aspace-deployment/releases/tag/v2024-07-05) with ArchivesSpace 3.5.0 is now live on Test. @erussey this ticket is ready for testing.

**Comment by erussey** [comment] 2024-07-24 19:42
@abelemlih : I just sent an email to Lyrasis...it looks like our data in Test is corrupted.  I've asked for a data refresh to hopefully address the issue with repositories.  The container display you addressed in the latest local Emory plug-in is fixed.

**Comment by erussey** [comment] 2024-08-09 16:07
@alexBLR : This ticket can probably be closed once 3.5.1 is deployed.  I'd like to keep it for now since it documents the issues that were fixed in our ASpace plug-in for 3.5.

**Closed as completed** 2024-12-11 16:19 UTC
Labels: backend
